{% set python_min = "3.9" %}
{% set name = "asesurfacefinder" %}
{% set version = "1.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/asesurfacefinder-{{ version }}.tar.gz
  sha256: 49e5d7da3f2dc443123982f1253a0d114ee370b05ab2867e50af5de8d9734a3d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=75.0.0
    - wheel
    - pip
  run:
    - python >={{ python_min }}
    - numpy
    - scipy
    - scikit-learn
    - dscribe
    - ase
    - matplotlib-base
    - sparse >=0.15

test:
  imports:
    - asesurfacefinder
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/joegilkes/ASESurfaceFinder
  summary: Machine learned location of chemical adsorbates on high-symmetry surface sites.
  description: |
    ASESurfaceFinder is an automated training suite for random forest classification
    models that can predict surface facets and high-symmetry adsorption sites when
    presented with ASE-based atomic surface/adsorbate systems.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - joegilkes
